### ISSUE TITLE
Popup to allow website to use micro are not shown

### ISSUE THREAD

**Issue by Kyuzial** [gcarq/inox-patchset#10]
Hi,
They don't appear on every website which should use the micro.
You can test it on https://discordapp.com for example.
Lastest version on archlinux.
Thanks

**Comment by gcarq** [comment]
I will look at this asap

**Comment by ganlub** [comment]
Hi,
Same here! With chromium it works.
You can test it here: https://appear.in/ganlub

**Comment by ArchGalileu** [comment]
For me also :(

Please... Pleaseee....

Best regards
ArchGalileu

**Comment by DragoonAethis** [comment]
Permission popup shows up fine on 61, this can be closed.
