### ISSUE TITLE
area51...by nyancat18

### ISSUE THREAD

**Issue by nyancat18** [gcarq/inox-patchset#101]
if somebody wants, please change tittle *lol*

scenario
* Chromium team has released the last chromium beta before chromium62
* Unless a major disaster happens **cve**  they may keep the same file at stable branch

for it i'm planning
* recycle the chromium-devel pkgbuild and adapt it for inox ... DONE
* adapt patches for work,  TODO
>  if it works it may be avaible at O2-14:00
* give a binary

**Comment by nyancat18** [comment]
about this

i've discovered some offensive errors (i've tried with inox pkgbuild)  and at some libraries i get clang errors

and its impossible to build, *i've thought that chromium-devs keeps this libs for save your time*,  but it safes **your package**


for it i'm replacing the pkgbuild with chromium-devs pkgbuild + inox +ug +iridium patches

**Comment by nyancat18** [comment]
its building 

>now are 29K steps 

i've found 2 dangers
>/third_party/crc32c
>>/third_party/leveldatabase

needs add this flag   -std=c++17

**Comment by nyancat18** [comment]
@gcarq @xsmile @eloston @perfect7gentleman @mayurifag @csmk @hasufell @dragoonaethis

if its possible,  i'll migrate the discussion to #102

**Comment by csmk** [comment]
Why ping so many people? The impatience is strong with this one.

Sorry, I'm out of the loop. _kthxbye!_

**Comment by Eloston** [comment]
@csmk 

> The impatience is strong with this one.

Really? Looks like @nyancat18's normal behavior to me. Perhaps you'd like to watch Inox and ungoogled-chromium repos...

Anyways, this issue is really confusing me. What's with the title? Is it clickbait? Why does this exists at all? At least the other issues made more sense...

**Comment by nyancat18** [comment]
itsnt clickbait

its only that i want try to help  
>to mantain   inox :)

and i've discovered some troubles  (if i can put a working binary, i'll post it)

**Comment by nyancat18** [comment]
pd
@csmk i understand

and if you want know

i've an "almost" working prototype (killing some patches)...and begining with some experiments "make sleep" mdns

>for know i dont know how kill it, but if i sleep it...its ok
