### ISSUE TITLE
How extension are updated since it shouldn't.

### ISSUE THREAD

**Issue by ThePierrezou** [gcarq/inox-patchset#11]
Hi,
Ublock origin has been updated, and normally it shouldn't (you said it in the readme.md).
Can someone explain it ?
Thanks
ThePierrezou

**Comment by gcarq** [comment]
This is because uBlock Origin has its own update logic which is independent from WebStore (please correct me), otherwise it wouldn't update automatically.

**Comment by gcarq** [comment]
I close this issue. Feel free to reopen if more infos are available.
