### ISSUE TITLE
Iridium browser

### ISSUE THREAD

**Issue by dimqua** [gcarq/inox-patchset#114]
How Inox is compared to Iridium? I mean, can you tell me please which impovements from Iridium are missing in Inox (if there're any) and visa versa?

**Comment by gcarq** [comment]
I don't know exactly, without looking. But one of the major differences is that Iridium marks many internal calls with a `trk:` prefix (I'm not sure if they are prefixing every URL), that leads to fewer leaks, but potential side-effects. In Inox it could be possible that some URLs are leaking if you have a edge use-case (until patched ofc).

You can look in their git repo: https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/
Here is also a diff of their repo from [chromium-61.0.3163.100 up to iridium-2017.10](https://git.iridiumbrowser.de/cgit.cgi/iridium-browser/diff/?h=61.0.3163.100&id=71dcce4f8689f59dde7238ec174af31a9cdb04c3&id2=7accc8730b0f99b5e7c0702ea89d1fa7c17bfe33), you can skip most *.grd resources as they mostly contain branding.

The Inox patches are described in the README.

**Comment by dimqua** [comment]
@gcarq why do you [mention](https://github.com/gcarq/inox-patchset#credits) Iridium in the README? I thought that you share some code with this project.

**Comment by gcarq** [comment]
@dimqua When I started this project, it contained almost all patches from Iridium, except the trk scheme and some other patch I can't remember right no. This was true in 2016. I don't know how much changed since then.
