### ISSUE TITLE
AUR packages flagged out of date

### ISSUE THREAD

**Issue by glitsj16** [gcarq/inox-patchset#12]
Hi, really appreciate your efforts. Iron runs just great on Arch Linux. Both AUR packages have been flagged out-of-date, any info on a pending update for 48.0.2564.116?

**Comment by gcarq** [comment]
Hi, I'm glad you like it. I just released 48.0.2564.116

**Comment by glitsj16** [comment]
Thanks for the response & the update! Looking good and consequently closing this issue/question.

**Comment by OhDaeto** [comment]
Please, bump Inox version on AUR.
https://r208.tk/OhDaeto/package_inox/commit/0c97c12c8d07e0c279bb6f0236c678c7b142026c
