### ISSUE TITLE
Webrtc switch

### ISSUE THREAD

**Issue by bn0785ac** [gcarq/inox-patchset#129]
since webrtc cant be disabled
and only could be "mitigated"

could you add something like
https://www.slimjet.com/en/how-to-disable-webrtc-in-chrome.php

**i know** slimjet its propietary, but may be fine emulate this (at flags OR just as they do)

**Comment by gcarq** [comment]
I don't see the benefit in adding this because it is proprietary.
Right now blocking webRTC with ublock origin or the like seems to be the best way.
