### ISSUE TITLE
Patch updates for Chromium 49

### ISSUE THREAD

**Issue by OhDaeto** [gcarq/inox-patchset#13]
I try prepare patches for Chromium 49 and I want to clarify the second part of the disable-autofill-download-manager.patch. What he removes?

**Comment by gcarq** [comment]
The `disable-autofill-download-manager.patch` "mocks" AutofillDownloadManager::StartRequest() and just returns true, so it won't upload any pre-filled form data.

I solved it this way because the local FormAutofill feature is still functional

**Comment by OhDaeto** [comment]
Updated patch. 
https://r208.tk/OhDaeto/inox-patchset/raw/d3f0635afaa93339bad7ba6b2a2aeb9133799487/disable-autofill-download-manager.patch

**Comment by gcarq** [comment]
Thanks! is this the only patch which needs a rewrite for version 49? I haven't looked into it yet.

**Comment by OhDaeto** [comment]
No! 😁 It's Only The Beginning! Now i `m inspecting disable-default-extensions.patch

**Comment by gcarq** [comment]
Oh ok 😁. I renamed this issue and keep it open to track outstanding patch updates. I will also look into on WE.

**Comment by OhDaeto** [comment]
Fixed
https://r208.tk/OhDaeto/inox-patchset/raw/b22c62f593cd76ca43288f9d6b30f260b3da4ba2/disable-default-extensions.patch

**Comment by OhDaeto** [comment]
Please help with disable-notification-promo-fetch.patch and chrome/browser/browser_process_impl.cc file!

**Comment by Eloston** [comment]
@OhDaeto: It seems that the code was moved out of that file. Here's a patch I just added that should have the same effect: https://github.com/Eloston/ungoogled-chromium/blob/master/patches/ungoogled-chromium/disable-web-resource-service.patch

**Comment by gcarq** [comment]
Released version 49.0.2623.110
