### ISSUE TITLE
Extension: CryptoTokenExtension

### ISSUE THREAD

**Issue by Primokorn** [gcarq/inox-patchset#132]
Hi,
Why do I have this built-in extension and **how can I remove/disable it**?
Current version: 0.9.46
 
EDIT
https://askubuntu.com/questions/844090/what-is-cryptotokenextension-in-chromium-extensions

**Comment by gcarq** [comment]
Thanks for the link. I'll look into it.

@Primokorn For now you can look at https://github.com/gcarq/inox-patchset/blob/master/0005-disable-default-extensions.patch and look for the extension in the related files. It should be loaded there somewhere.

**Comment by Eloston** [comment]
Does leaving this extension in do any harm? I don't know how this extension works.

I remember there was a user in the past that used 2FA with ungoogled-chromium, so I'm not as willing to disable it if it can't do anything on its own (2FA required another extension from Google to work).

**Comment by gcarq** [comment]
@Eloston I would also leave it in place if it doesn't do any harm, there valid reasons for using 2FA
