### ISSUE TITLE
Please update the binary in the AUR

### ISSUE THREAD

**Issue by sirx** [gcarq/inox-patchset#134]
I had to switch to normal chromium since Inox hasnt getting security updates at all and is vulnerable to this piece of javascript right now!

http://xlab.tencent.com/special/spectre/spectre_check.html

Please update, thanks!

**Comment by gcarq** [comment]
I'll publish an AUR update in a few hours

**Comment by sirx** [comment]
Thanks!

**Comment by gcarq** [comment]
Updated
