### ISSUE TITLE
incognito colors

### ISSUE THREAD

**Issue by gothmog123** [gcarq/inox-patchset#136]
Just a minor issue but the incognito new tab page is all white even if you're using dark themes which looks kind of out of place.

**Comment by xsmile** [comment]
0008-restore-classic-ntp.patch causes this behavior. I believe it should be safe to restore the default incognito page.

By the way, the incognito page stays dark if you use a light theme by default.

@gcarq I did the change in feature/64 as the patch needed adjustments anyway and I didn't see any unwanted traffic. Can you verify it please? See the [source of v64](https://chromium.googlesource.com/chromium/src.git/+/64.0.3282.105/chrome/browser/search/search.cc#139), the [current patch](https://github.com/gcarq/inox-patchset/blob/master/0008-restore-classic-ntp.patch#L3) and the [new patch](https://github.com/gcarq/inox-patchset/blob/feature/64/0008-restore-classic-ntp.patch#L3).

**Comment by gothmog123** [comment]
thank you

**Comment by gcarq** [comment]
Sorry I didn't see that mention. Looks fine to me as well. I'm closing this, feel free to reopen if this is still an issue
