### ISSUE TITLE
Whatsapp

### ISSUE THREAD

**Issue by Nycex** [gcarq/inox-patchset#147]
At web.whatsapp.com the qrcode shows for 0.1 second and then disappears. I tried to disable all extensions and it didnt work.

**Comment by xsmile** [comment]
No such issue here with inox-bin 65.0.3325.162 from the AUR.

Try to start the browser with `inox --user-data-dir=/tmp/inox-profile --disable-extensions` and see if the problem persists.

**Comment by Nycex** [comment]
Yeah, still the problem, and im using inox-bin too.

**Comment by Nycex** [comment]
I reinstalled it, didn't work either.

**Comment by xsmile** [comment]
Does it happen with the official Chromium package with a new browser profile?

**Comment by Nycex** [comment]
Yes, thats not working either.
