### ISSUE TITLE
ICU Libraries Issue

### ISSUE THREAD

**Issue by LearnPhalcon** [gcarq/inox-patchset#148]
Version Issues: 65.0.3325.181
Arch Linux Packages:
- icu 61.1-1
- harfbuzz-icu 1.7.6.2

`/usr/lib/inox/inox: error while loading shared libraries: libicui18n.so.60: cannot open shared object file: No such file or directory`

`/usr/lib/inox/inox: error while loading shared libraries: libicuuc.so.61: cannot open shared object file: No such file or directory`

**Comment by LearnPhalcon** [comment]
I can confirm, its fixed now. Thank You @gcarq

**Comment by d-packs** [comment]
Hi the same issue cropped up upon system update:
`/usr/lib/inox/inox: error while loading shared libraries: libicui18n.so.61: cannot open shared object file: No such file or directory`

Inox Version: inox-bin  67.0.3396.87-1
Arch Linux Packages

- local/harfbuzz-icu 1.8.7-1   
- local/icu 62.1-1   
- local/lib32-icu 62.1-1
