### ISSUE TITLE
Not starting on Manjaro

### ISSUE THREAD

**Issue by Phoenix1747** [gcarq/inox-patchset#149]
When trying to launch the latest inox version (65.0.3325.181-2) the following error message pops up:
```
/usr/lib/inox/inox: error while loading shared libraries: libicui18n.so.61:
cannot open shared object file: No such file or directory
```

System: Manjaro

Tested with both the AUR package `inox-bin` and the release .tar.xz here on Github. This might as well apply to arch itself.

**Comment by xsmile** [comment]
Manjaro should have
