### ISSUE TITLE
Incorrect GYP flag for disabling safe browsing

### ISSUE THREAD

**Issue by Eloston** [gcarq/inox-patchset#15]
@perfect7gentleman noticed that Inox still mentions `safe_browsing_mode` as the GYP flag to disable safe browsing (in the README and [here](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=inox#n186)). The flag is now called `safe_browsing`.

If you are going to use this flag, you will need to patch the source code to make the build work. [This patch](https://github.com/Eloston/ungoogled-chromium/blob/master/patches/ungoogled-chromium/fix-building-without-safebrowsing.patch) contains the modifications necessary.

**Comment by perfect7gentleman** [comment]
safe_browsing_mode is GN flag.
https://chromium.googlesource.com/chromium/src/+/master/tools/gn/docs/cookbook.md#Feature-flags

**Comment by Eloston** [comment]
Inox [uses the GYP configuration system](https://aur.archlinux.org/cgit/aur.git/tree/PKGBUILD?h=inox#n209), so those flags won't work.

**Comment by Eloston** [comment]
#29 closes this.
