### ISSUE TITLE
[REQUEST] Patches Information Page

### ISSUE THREAD

**Issue by v00v** [gcarq/inox-patchset#153]
Can we have a page like "about:patches" (chrome://patches/) were we can see what patches are used in Inox. Maybe even with information like who made the patch and when. Thank you.

**Comment by Eloston** [comment]
What benefits does this provide over viewing the repo and using git-blame? The patch names aren't always descriptive of the contents.

**Comment by gcarq** [comment]
I also think it is better to use git-blame or just visiting the github page for the same reason.
