### ISSUE TITLE
libicui18n.so.61 issue

### ISSUE THREAD

**Issue by v00v** [gcarq/inox-patchset#159]
Error in Arch Linux after latest update on August 8th, 2018
```
/usr/lib/inox/inox: error while loading shared libraries: libicui18n.so.61: 
cannot open shared object file: No such file or directory
```

**Comment by d-packs** [comment]
Hello it seems this is the same error as #148
`/usr/lib/inox/inox: error while loading shared libraries: libicui18n.so.61: cannot open shared object file: No such file or directory`

Arch Linux packages state:
- local/harfbuzz-icu 1.8.7-1
- local/icu 62.1-1
- local/lib32-icu 62.1-1

Inox Version: inox-bin 67.0.3396.87-1

**Comment by v00v** [comment]
@d-packs, Yes this is correct. "harfbuzz" and "icu" seems to break Inox anytime there is a new version. I can confirm that it doesn't work with "harfbuzz-icu 1.8.8-1" version too. And re-compiling Inox myself takes forever, hardware is just too old. So please fix this issue, by releasing new updated Inox version that works. Thank You!

**Comment by v00v** [comment]
It seems that you can manually copy those library files to make it work. Here is a temporary workaround.

* Download and Install old "icu" package;
``https://archive.archlinux.org/packages/i/icu/icu-62.1-1-x86_64.pkg.tar.xz``
* Copy all "icu" files to a backup directory;
``sudo mkdir /usr/lib/backup``
``sudo cp -r /usr/lib/libicu* /usr/lib/backup/``
* Install new version of "icu" again;
``sudo pacman -U /var/cache/pacman/pkg/icu-62.1-1-x86_64.pkg.tar.xz``
* Copy this three files back to /var/lib/ direcotry;
``sudo cp /var/lib/libicui18n.so.61 /usr/lib/``
``sudo cp /var/lib/libicuuc.so.61 /usr/lib/``
``sudo cp /var/lib/libicudata.so.61 /usr/lib/``
This should do it. If it still doesn't work for you, run "inox" command in your terminal to see which other files you need to copy.
* You can now cleanup backup files;
``sudo rm -rf /var/lib/backup``

**Comment by Thrilleratplay** [comment]
I switched from `inox-bin` to `inox`.  It takes a while to compile but fixes the issue.

**Comment by v00v** [comment]
This above workaround is for existing installed inox. But if you want to use latest version of Chrome then recompiling is the way to go. But remember that the latest version of Chrome can have new features wich may prevent existing patches from working correctly.

**Comment by keescpk** [comment]
Have tried the workaround but it did not "work" for me , so based on the workaround, here is what i did.
In the first two lines i replaced icu-62.1-1x86_64.pkg with icu-61.1-1-x86_64.pkg.tar.xz. Next i copied the files libicui8n.so61.1 from /usr/lib/backup to /usr/lib. And did the same with the files libicuuc.so.61.1 as well as libicudata.so61.1.

**Comment by lightdot** [comment]
The only proper way to fix this is to rebuild the inox (inox-bin) package.

In the mean time, this indeed works:

````
curl -Lo /tmp/icu-61.1-1-x86_64.pkg.tar.xz https://archive.archlinux.org/packages/i/icu/icu-61.1-1-x86_64.pkg.tar.xz
tar --wildcards --no-anchored --warning=none -xvf /tmp/icu-61.1-1-x86_64.pkg.tar.xz *libicudata.so.61* *libicui18n.so.61* *libicuuc.so.61*
sudo mv /tmp/usr/lib/libicu*.so.61* /usr/lib
rm /tmp/icu-61.1-1-x86_64.pkg.tar.xz
rm -r /tmp/usr
````
Don't forget to remove /usr/lib/libicu*.so.61* after inox has been rebuilt or updated:
````
sudo rm /usr/lib/libicu*.so.61*
````

**Comment by v00v** [comment]
Switching to "Ungoogled-Chromium" if anyone cares, as Inox no longer updated!
You can find it here; https://github.com/Eloston/ungoogled-chromium
