### ISSUE TITLE
New Chromium Version

### ISSUE THREAD

**Issue by ghost** [gcarq/inox-patchset#163]
Hey Michael, first of all thank you for "Inox Patchset" this is one of the best browsers around. But you need to update to newer versions more often or at least allow others to join to do this when you don't have time.

Since Current Inox Version 67.0.3396.87 (Released: 2018-05-29) there has been many fixes and improvements in Chromium Version 69.0.3497 (Released: 2018-09-04) [1]

#### Version 69.0.3497 (Released: 2018-09-04) [Stable]
* New browser interface.
* CSS Scroll Snap allows you to create smooth, slick, scroll experiences.
* Display Cutouts lets you use the full area of the screen, including any space behind the display cutout, sometimes called a notch.
* The Web Locks API allows you to asynchronously acquire a lock, hold it while work is performed, then release it.
* From the CSS4 spec, you can now create color transitions around the circumference of a circle, using conic gradients.
* New toggleAttribute() method on elements toggles the existence of an attribute, similar to classList.toggle().
* JavaScript arrays are getting two new methods: flat() and flatMap().
* OffscreenCanvas moves work off the main thread in a worker, helping to eliminate performance bottlenecks.
(More: https://chromereleases.googleblog.com/2018/09/stable-channel-update-for-desktop.html)

#### Version 68.0.3440 (Released: 2018-07-24) [Discontinued]
* HTTP sites marked as "not secure".
* The Page Lifecycle API tells you when your tab has been suspended or restored.
* The Payment Handler API makes it possible for web-based payment apps to support the Payment Request experience.
* Content embedded in an iframe requires a user gesture to navigate the top-level browsing context to a different origin.
* Since Chrome 1, the CSS cursor values for grab and grabbing have been prefixed; standard, un-prefixed values now supported.
(More: https://en.wikipedia.org/wiki/Google_Chrome_version_history#cite_note-Chrome_68-164)

#### Version 67.0.3396 (Released: 2018-05-29) [Discontinued]
* Progressive Web Apps are coming to the desktop.
* The generic sensor API makes it way easier to get access to device sensors like the accelerometer, gyroscope and more.
* BigInt's make dealing with big integers way easier.
* Credential Management API provides a framework for creating, retrieving and storing credentials.
* The Web Authentication API adds a third credential type, PublicKeyCredential, which allows browsers to authenticate a user with a private/public key pair generated by an authenticator.
(More: https://chromereleases.googleblog.com/2018/05/stable-channel-update-for-desktop_58.html)

1. https://chromereleases.googleblog.com/2018/10/stable-channel-update-for-chrome-os.html
2. https://en.wikipedia.org/wiki/Google_Chrome_version_history
3. https://chromereleases.googleblog.com/

**Comment by v00v** [comment]
Nevermind, Inox seems dead now!
