### ISSUE TITLE
Change icon?

### ISSUE THREAD

**Issue by sanderboom** [gcarq/inox-patchset#17]
First of all: thanks for this effort!

Second: would it be possible to use a variation of the typical Chromium icon? Obviously this would distinguish the Inox windows from the Chromium windows in taskbar, window switchers, etc. 

 As a - simple, but sufficiently different - example the current icon desaturated:
![inox](https://cloud.githubusercontent.com/assets/5956570/15463873/5a8f7526-20cc-11e6-9055-54422d5418aa.png)

**Comment by gcarq** [comment]
I like that idea

**Comment by sanderboom** [comment]
Implemented for Arch linux AUR package. See diff: https://github.com/sanderboom/arch-aur-inox/commit/0b73810f4e2c1ffd6702ac37410a20be34bea27e

**Comment by gcarq** [comment]
Added with release [53.0.2785.89](https://github.com/gcarq/inox-patchset/releases/tag/53.0.2785.89).

**Comment by sanderboom** [comment]
Awesome. Thanks!
