### ISSUE TITLE
Patchset for Windows ?

### ISSUE THREAD

**Issue by samfirta** [gcarq/inox-patchset#22]
Could I apply the patches under Windows?

I tried it and I am getting the message "patch format detection failed".

**Comment by gcarq** [comment]
I think the "patch format detection failed" comes from the patch header, which currently looks in most files like this:
```
--- ./components/search_engines/prepopulated_engines.json
+++ ./components/search_engines/prepopulated_engines.json.new
```
but a standard git patch header should looks like:
```
--- a/components/search_engines/prepopulated_engines.json
+++ b/components/search_engines/prepopulated_engines.json
```

The patches itself should work on windows, at least most of them, but it's possible that some of them are only modifying linux specific code. Make sure you apply the chromium branding with `-Dbranding=Chromium`

**Comment by gcarq** [comment]
[ungoogled-chromium](https://github.com/Eloston/ungoogled-chromium/releases) provides prebuilt binary packages and a [HOWTO](https://github.com/Eloston/ungoogled-chromium/blob/master/BUILDING.md) for building windows.
