### ISSUE TITLE
Could you add the VA-API patch?

### ISSUE THREAD

**Issue by HighIO** [gcarq/inox-patchset#24]
https://aur.archlinux.org/packages/chromium-vaapi/
It is compiled with support for VA-API originally from https://raw.githubusercontent.com/saiarcot895/chromium-ubuntu-build/master/debian/patches/enable_vaapi_on_linux.diff

**Comment by gcarq** [comment]
Has this patch some downsides if VA-API acceleration is not available?

**Comment by DragoonAethis** [comment]
Status at the moment:

- VA-API on Chromium 54 is broken by upstream, but is apparently fixed and going to be released with Chromium 55 soon.
- This patch requires two separate builds for Intel and "other" drivers (Radeon/NVIDIA/etc).
- The Intel patch works on X11, Wayland and Ozone (Chrome OS display manager), "other" works only on X11.
- Intel driver also works on systems with multiple GPUs, eg with Intel iGPU and Radeon/NVIDIA dGPU (Optimus systems).
- If VA-API isn't available, Chromium will fall back to software decoding (as is the case today for everyone).
- There's a GPU blacklist which prevents VA-API from initializing with buggy drivers/GPUs.

How about building with the VA-API patch for Intel once Chromium 55 is out? The patch should be refactored to support all drivers eventually, but it seems to be a bit more "clean", plus it's tested on x86-based Chromebooks pretty well.

**Comment by forkoz** [comment]
heh, I'm using chromium 56 today with FGLRX and decoding is working from this ppa: https://launchpad.net/%7Esaiarcot895/+archive/ubuntu/chromium-dev

only thing not working is native GPU memory buffers but I think that is intel only? multiple raster threads have the eat all your memory bug but single thread rendering is fine. radeontop shows heavy usage when the video is playing and comparable videos don't play in firefox without tears and stutters. FF also doesn't accelerate flash despite being the exact same flash through freshplayer.

**Comment by Eloston** [comment]
@forkoz 

> radeontop shows heavy usage when the video is playing

Do you mean CPU usage? Then it's very likely that VA-API acceleration is not working. There are some bugs reported on the GitHub repo of that PPA where the module loads successfully but it doesn't accelerate. They were also disabling the GPU sandbox.

Oh and you can't check video acceleration status via `chrome://gpu`. That only tells you if it can attempt hardware acceleration, not if it is working.

> only thing not working is native GPU memory buffers but I think that is intel only?

There is progress on hardware-acceleated Native GPU Memory Buffers with Intel processors on Chrome OS, so that may be the only chance to get that feature on Linux. Otherwise it's not supported on any desktop OS as far as I know.

**Comment by DragoonAethis** [comment]
@Eloston radeontop measures GPU usage. Also, 57/58 is right about the corner, [and the related patch in that PPA was updated for 58 recently](https://github.com/saiarcot895/chromium-ubuntu-build/blob/master/debian/patches/enable_vaapi_on_linux.diff) (see History for 57), so it might be worth migrating to a newer version first.

**Comment by xsmile** [comment]
Looks like chromium will support VA-API without modifications soon:
http://www.phoronix.com/scan.php?page=news_item&px=Chrome-VA-API-Nears

**Comment by DragoonAethis** [comment]
As of 61, VA-API support is included and seems to be working fine on Intel GPUs. This can be closed.
