### ISSUE TITLE
Libvpx error 

### ISSUE THREAD

**Issue by stelariusinfinitek** [gcarq/inox-patchset#26]
Arch Linux received an update for libvpx recently and it affects Inox. Sadly, Inox is not starting anymore...  
  
The error : 

/usr/lib/inox/inox: error while loading shared libraries: libvpx.so.3: cannot open shared object file: No such file or directory  
  
The new file, after update, is called libvpx.so.4

**Comment by stelariusinfinitek** [comment]
I miss Inox :( It was so damn good. The dev is probably enjoying the summer, I hope he will be back. Right now I think Inox doesn't work for any Arch user anymore.

**Comment by Thrilleratplay** [comment]
@stelariusinfinitek  Sorry, I should have posted the temporary work around

```
sudo ln -s /usr/lib/libvpx.so.4 /usr/lib/libvpx.so.3 
```

**Comment by OhDaeto** [comment]
@stelariusinfinitek, did you try recompile Inox?

**Comment by stelariusinfinitek** [comment]
@Thrilleratplay If it works, thank you so much! Will test it in a moment.

@OhDaeto I use inox-bin. Do you have any idea how much it will take to compile on a PC with 1,8 Ghz Dual-Core CPU? I fear it will take too long.

**Comment by catt0** [comment]
I ran into troubles when trying to use youtube with that workaround. Instead I extracted version 3 of libvpx from the old libvpx package and added it to /usr/lib. You can get the old version either from your package cache or https://archive.archlinux.org/packages/l/libvpx/
Be careful not to overwrite the newer version, to get inox to run it is enough to have /usr/lib/libvpx.so.3

**Comment by stelariusinfinitek** [comment]
Yeah I had the same problem with Youtube. Right now I want to wait for the dev to update Inox.

**Comment by stelariusinfinitek** [comment]
The dev is back, I'm so happy that a new release is coming soon. Closing this. :)
