### ISSUE TITLE
ETA for updates?   

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#28]
when you gonna give updates from inox?  

because inox is broken (by an arch linux vpx update), and must be rebuild, linking to the new version of libvpx, or you caon't watch youtube videos

**Comment by stelariusinfinitek** [comment]
He is working on it! :)

**Comment by gcarq** [comment]
ETA: 30 min :)

**Comment by gcarq** [comment]
Released version [53.0.2785.89](https://github.com/gcarq/inox-patchset/releases/tag/53.0.2785.89).
