### ISSUE TITLE
disable-new-avatar-menu.patch breaks user profile switching on macOS

### ISSUE THREAD

**Issue by Eloston** [gcarq/inox-patchset#32]
Patching `avatar_menu.cc` with the code in `disable-new-avatar-menu.patch` prevents users from switching profiles on macOS.

I have not seen any other side effects of reverting the patch on this file. See [this issue](https://github.com/Eloston/ungoogled-chromium/issues/45) for more details.

**Comment by gcarq** [comment]
I rewrote this patch with release [56.0.2924.87](https://github.com/gcarq/inox-patchset/releases/tag/56.0.2924.87), please check if this issue still exists (feel free to repoen this issue).
