### ISSUE TITLE
Widevine not working

### ISSUE THREAD

**Issue by timmykill** [gcarq/inox-patchset#33]
Is there a way to compile chromium-widevine(aur) and make it work on inox?

**Comment by Eloston** [comment]
Did you already install `libwidevinecdm.so` and `libwidevinecdmadapter.so`?

**Comment by gcarq** [comment]
You can symlink `libwidevinecdm.so` from `/usr/lib/chromium` to `/usr/lib/inox` if you have chromium-widevine installed, or modify chromium-widevine PKGBUILD to install it for you in `/usr/lib/inox`

**Comment by timmykill** [comment]
Thank you both
