### ISSUE TITLE
ETA?: Chrome 54

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#37]
Chromium has version 54, eta for update.

thanks

**Comment by cryzed** [comment]
See [here](https://github.com/gcarq/inox-patchset/issues/36#issuecomment-260721407).

**Comment by triceratops1** [comment]
@cryzed   

as i understand, inox gonna use seleniun (and upgrade after this change works)?

**Comment by cryzed** [comment]
No, the author gave an ETA in the post I linked.

**Comment by gcarq** [comment]
I upgraded the patches in a local branch, next step is to upgrade from GYP to GN build process. A build can be expected tonight or tomorrow.

**Comment by gcarq** [comment]
Released version [54.0.2840.100](https://github.com/gcarq/inox-patchset/releases/tag/54.0.2840.100), AUR packages for inox and inox-bin are also updated.
