### ISSUE TITLE
Inox54 cups issue

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#38]
when i am trying to compile inox  54

i get this issues
../../printing/backend/print_backend_cups.cc:243:21: error: use of undeclared identifier 'cupsGetPPD'

**Comment by triceratops1** [comment]
https://github.com/triceratops1/inoxy

**Comment by gcarq** [comment]
Fixed with version 54. I switched to gn build system with this release and `use_cups=true` fixes this issue.

**Comment by triceratops1** [comment]
thanks
