### ISSUE TITLE
uBlock Origin crashes

### ISSUE THREAD

**Issue by RomanSC** [gcarq/inox-patchset#4]
Great work, thanks for putting this together!

I installed uBlock Origin from the web store with the instructions given, for some reason the extension crashes as soon as it's started. All of my other extensions work flawlessly as far as I can tell.

Any troubleshooting methods I can try?

Thanks

**Comment by DragoonAethis** [comment]
This is actually an issue with Chromium - if you build the browser w/o WebRTC support, calling any WebRTC functions (even if the browser properly reports these as unavailable) = crash.

Should you visit src/js/start.js and remove `'webrtcIPAddress': !userSettings.webrtcIPAddressHidden` plus the comma on the previous line, uBlock won't crash anymore. (Obviously, touching WebRTC settings in uBlock settings will change that :P) This was reported in uBlock repo, but closed as it is an upstream Chromium issue.

**Comment by RomanSC** [comment]
So if I'm understanding correctly, I can re-enable WebRTC after I've installed inox and built from the AUR?

**Comment by DragoonAethis** [comment]
If you try to toggle the WebRTC setting in uBlock settings, uBlock browser process will crash. If you re-enable WebRTC in your Inox build, sure, it'll work fine.

**Comment by gcarq** [comment]
uBlock Origin 1.4.1b resolves this issue, see: https://github.com/gorhill/uBlock/issues/533

**Comment by gcarq** [comment]
Fix integrated with Release build 1.5.3b
