### ISSUE TITLE
Several patches updated for 55.0.2883.75

### ISSUE THREAD

**Issue by Eloston** [gcarq/inox-patchset#43]
[I've updated my subset of Inox patches to Chromium 55](https://github.com/Eloston/ungoogled-chromium/tree/55.0.2883.75-1/resources/common/patches/inox-patchset). One or two of them are missing some small changes to remove redundancy with Debian's patches.

If you want it in a PR, let me know.

**Comment by triceratops1** [comment]
i've "achified" the @eloston  safe browsing patch   
https://gist.github.com/triceratops1/ea3d11c8cc148f6235a3d29fc72ebed1

**Comment by gcarq** [comment]
Thanks, works like a charm! No PR is needed. I've also updated [chromium-sandbox-pie.patch](https://github.com/gcarq/inox-patchset/blob/master/chromium-sandbox-pie.patch) to set the correct flag for GN builds.

**Comment by Eloston** [comment]
@gcarq Oh cool thanks for the updated version of that patch.
