### ISSUE TITLE
Privacy Badger Extension Always Crashing

### ISSUE THREAD

**Issue by benjaminrich** [gcarq/inox-patchset#48]
I installed the [Privacy Badger](https://www.eff.org/privacybadger) extension as described. I think it was working for a while, but now it is always crashing. I tried to reinstall (the extension, not Inox), but still crashing.

Privacy Badger seems like a good extension to prevent tracking. Don't know if it is necessary to have such an extension with Inox.

**Comment by csmk** [comment]
Give a try to [uBlock Origin](https://chrome.google.com/webstore/detail/ublock-origin/cjpalhdlnbpafiamejdnhcphjbkeiagm). It's running pretty fine here.

**Comment by perfect7gentleman** [comment]
uBlock Origin + uMatrix is enough.

**Comment by benjaminrich** [comment]
Thanks. I may give it a try. I'm less concerned about adds than about being tracked. I still think it would be good to know why the Privacy Badger extension crashes, though, since it works in chromium.

**Comment by Eloston** [comment]
Wild guess, but it could be the lack of WebRTC support. I remember uBlock Origin had to be fixed so it wouldn't crash on browsers without WebRTC support.

**Comment by triceratops1** [comment]
@eloston 

i've issues with badger  disabling webrtc
at other browser


for them i use ublock+umatrix + scriptsafe

**Comment by gcarq** [comment]
@benjaminrich: As @Eloston mentioned this seems to be an Privacy Badger issue. They merged a potential fix a while ago (https://github.com/EFForg/privacybadger/pull/1108), could you please test again with the latest Privacy Badger version?

**Comment by gcarq** [comment]
Should be fixed with [57.0.2987.133](https://github.com/gcarq/inox-patchset/releases/tag/57.0.2987.133), because webrtc is enabled by default.
