### ISSUE TITLE
Pepper Flash

### ISSUE THREAD

**Issue by RomanSC** [gcarq/inox-patchset#5]
Where should I start with trying to configure pepper-flash to work in Inox so I can watch Flash content?

I've installed the chromium-pepper-flash package in Arch and it works for Chromium, I'd like to get it working in Inox so that I can use Inox exclusively

Thanks

**Comment by xDShot** [comment]
If you want to use flash, why ever you need Inox? Install Chromium and be happy.

**Comment by gcarq** [comment]
Never had an issue with chromium-pepper-flash and inox.

I checked the calling arguments on my system with a new profile:
```
/usr/lib/inox/inox --ppapi-flash-path=/usr/lib/PepperFlash/libpepflashplayer.so --ppapi-flash-version=19.0.0.226
```
Start with a fresh profile and if that doesn't work check /etc/chromium/default if the --ppapi-flash-path is correct.

@xDShot I see no point against using flash and inox if someone is sane enough to disable plugin-autorun.
