### ISSUE TITLE
question: how could i disable tests?   

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#51]
how could i disable google's tests + aboid compiling UNREQUIRED libraries (webrtc)?   

saving buildtime (precious if you dont have a paid vps)

**Comment by gcarq** [comment]
how are you invoking the build process?, If you are using the AUR PKGBUILD, tests are skipped and only necessary libraries are built. You can specify what you want to build with the GN flags.

**Comment by triceratops1** [comment]
@gcarq  but    wercker fails :(

**Comment by gcarq** [comment]
@triceratops1 Yes because unfortunately the build job hit the resource limit of wercker. Please ask questions in the related issues, in this case https://github.com/gcarq/inox-patchset/issues/42.
