### ISSUE TITLE
Update to version 56

### ISSUE THREAD

**Issue by gcarq** [gcarq/inox-patchset#54]
Work is in progress, if there are no unexpected changes version 56.0.2924.76 will be released tomorrow.

Testing branch: https://github.com/gcarq/inox-patchset/tree/update/56.0.2924.76
Relevant issues: https://github.com/gcarq/inox-patchset/issues/50

**Comment by perfect7gentleman** [comment]
cannot build Chromium with those patches.
@gcarq, did you test them?

**Comment by perfect7gentleman** [comment]
Built without webrtc & safe-browsing disabling patches

**Comment by gcarq** [comment]
It should build now with all patches.

**Comment by gcarq** [comment]
Version 56.0.2924.76 is released, keeping #50 open because it needs more time to evaluate
