### ISSUE TITLE
inox compilation with musl libc

### ISSUE THREAD

**Issue by Kokokokoka** [gcarq/inox-patchset#55]
Hello, I was trying to get inox patchset working on musl (http://git.alpinelinux.org/cgit/aports/tree/community/chromium?h=master), the thing is that on musl the shim allocator is replaced with none, 
and it still tries to compile it with name unifiedshim allocator, I would love to get inox patchset working,
could you be of assistance?

**Comment by gcarq** [comment]
AFAIK chromium doesn't support musl out of the box, but the alpine team crafted some patches to do so. There was a thread on a mailing list some times ago (link to patches is included): http://www.openwall.com/lists/musl/2016/03/18/20

**Comment by Kokokokoka** [comment]
Yes, I even linked those patches, but still, chromium tries to compile shim, on the second compilation step,
It tries to build _unified shim_, maybe I could fix this issue, but I don't know where to look, as it is not the tools/gn/bootstrap/bootstrap.py	
-        'base/allocator/allocator_shim.cc',
-        'base/allocator/allocator_shim_default_dispatch_to_glibc.cc',
and the first stage went flawlessly, it's the second step, I would like to find out where was the second step declared if not in the bootstrap.py

**Comment by gcarq** [comment]
On which distribution are you building this?
You can look at the chromium APKBUILD file from alpine linux, they are using some interesting build flags including:
```
-Duse_allocator=none
-Duse_experimental_allocator_shim=false
```

**Comment by Kokokokoka** [comment]
On exherbo it's a gentoo spinoff, with paludis and eclectic. I'll take a look. I think that was the thing that I've missed.

**Comment by gcarq** [comment]
you're welcome
