### ISSUE TITLE
Chromium 57 disables chrome://plugins

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#58]
Hi,   sorry if i disturb you

for chromium 57 gonna disable plugin control

how could we reenable it?   :D  

http://www.ghacks.net/2017/01/29/google-removes-plugin-controls-from-chrome/

**Comment by ivan** [comment]
It's already sort-of gone in Chrome 56, the Disable links in chrome://plugins/ still work but the state isn't  remembered after a browser restart.

**Comment by DragoonAethis** [comment]
Correct me if I'm wrong, but Inox doesn't come with Flash nor Widevine by default (or at least it somehow doesn't on my system), therefore there's no point?

**Comment by triceratops1** [comment]
@DragoonAethis  doesnt have it by default


but if you've installed it..

**Comment by Eloston** [comment]
There was some discussion about this here: https://github.com/Eloston/ungoogled-chromium/issues/181

**Comment by gcarq** [comment]
Thanks for the update. 

> Closing now, since all of the desired functionality is available in alternate forms.

Closing for the same reason.
