### ISSUE TITLE
Why bookmark manager is removed?

### ISSUE THREAD

**Issue by xDShot** [gcarq/inox-patchset#6]
Question.

**Comment by OhDaeto** [comment]
Some question

**Comment by gcarq** [comment]
My first thought was the bookmark manager is necessary to use the bookmark bar, import bookmarks, etc.., but as it turns out it is only needed for bookmark syncing between devices and nothing else. 
Please correct me if I'm wrong.

**Comment by xDShot** [comment]
By bookmark manager i meant menu item (Menu - Bookmarks - Bookmarks manager (Ctrl + Shift + O). It is used to manipulate bookmarks (edit, delete, move into another folder, etc.) which are saved locally. One of these patches removes it, so without it I can't manipulate them.

**Comment by gcarq** [comment]
Ah I see, I personally never used Bookmark manager to manipulate bookmarks.
I will add it again ASAP.

Until then if you want to re-enable it manually edit disable-default-extensions.patch [line 128-129](https://github.com/gcarq/inox-patchset/blob/master/disable-default-extensions.patch#L128-129) and [line 160](https://github.com/gcarq/inox-patchset/blob/master/disable-default-extensions.patch#L160).

**Comment by xDShot** [comment]
Thank you :)

**Comment by OhDaeto** [comment]
Thanks!
