### ISSUE TITLE
Request: Fix some vulns (update)

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#60]
chromium 	56.0.2924.87-1

https://security.archlinux.org/AVG-156

chromium has been updated against some vulns, sorry for disturb.

**best regards**

**Comment by gcarq** [comment]
Thanks for reporting. Most of the issues are already fixed with 56.0.2924.76, but you can expect the 56.0.2924.**87** release this weekend.

cheers

**Comment by triceratops1** [comment]
hi  

if you want
you could check layman repository (layman its like the gentoo's aur)  :P
http://data.gpo.zugaina.org/frabjous/www-client/inox/

**Comment by gcarq** [comment]
Released version [56.0.2924.87](https://github.com/gcarq/inox-patchset/releases/tag/56.0.2924.87).
