### ISSUE TITLE
Name the patch files in order

### ISSUE THREAD

**Issue by hasufell** [gcarq/inox-patchset#61]
This would make it easier for scripts to auto-apply all patches based on filename. Currently, if you try to patch based on the order of filenames, patches won't apply cleanly.

So they should be named `0001-disable-autofill-download-manager.patch` etc.

**Comment by Lourens-Rich** [comment]
Why you can't applying patches in PKGBUILD's order?

**Comment by hasufell** [comment]
You mean it's easier for people to look up the PKGBUILD for every new release to recreate the correct patch order manually instead of just applying them based on the filename?

**Comment by gcarq** [comment]
Good idea. It will be included in the next release.

**Comment by gcarq** [comment]
Fixed with release [56.0.2924.87](https://github.com/gcarq/inox-patchset/releases/tag/56.0.2924.87).
