### ISSUE TITLE
Request: Disable some sound frecuencies

### ISSUE THREAD

**Issue by nyancat18** [gcarq/inox-patchset#62]
the humans can't listen ultrasound, but the ultrasound gives you some risks

https://science.slashdot.org/story/17/01/05/2159219/ultrasound-tracking-could-be-used-to-deanonymize-tor-users

can you censor it?

thanks

**Comment by Eloston** [comment]
If using the JavaScript API, I believe Chromium is already configured by default to prompt the user for microphone access. So this isn't really an issue.

If you're using Flash, then that is mostly out of the control of the browser. Disable it, use click-to-play, or use a whitelist.

**Comment by triceratops1** [comment]
@eloston
1 uses JS API
but
2 its based at <audio>/<video> not microphone (you need forbide play ultrasound), the humans cant listen ultrasound, but some machines yes

**Comment by Eloston** [comment]
Here is the relevant section in the article:

> uXDT relies on advertisers hiding ultrasounds in their ads. When the ad plays on a TV or radio, or some ad code runs on a mobile or computer, it emits ultrasounds that get picked up by the microphone of nearby laptops, desktops, tablets or smartphones

Basically, this system requires that both ends actually work. One end that emits ultrasound (TV, radio, or mobile device) needs to be picked up by the other end (mobile devices).

So it seems that Chromium's microphone access control only solves half of the problem. To solve the other half, there isn't a easy solution that is certain to work. If the ads that play ultrasound are separate from the main content the user wants to view/listen to, then a blocking extension like uBlock Origin or an extension that selectively disables HTML5 audio autoplaying.

A better solution would be to filter out frequencies beyond what the ear is capable of hearing, but that would require some effort to figure out.

**Comment by triceratops1** [comment]
>A better solution would be to filter out frequencies beyond what the ear is capable of hearing, but that would require some effort to figure out.

yeah

:(
