### ISSUE TITLE
No access to most files?

### ISSUE THREAD

**Issue by faurehu** [gcarq/inox-patchset#63]
I'm trying to install extensions. When I try to load unpacked files, the file picker won't show me most folders in my home directory. If I drag and drop it, the browser will say the file can't be found.

I figured the browser doesn't have permission to read those files but I've checked and the user that starts the Inox process can rwx all of these.

For reference, I'm on Arch linux.

**Comment by gcarq** [comment]
AFAIK the file picker doesn't show hidden files beginning with `.` per default. Did you try to load the extension via the developer mode option?

**Comment by faurehu** [comment]
@gcarq The file picker is actually showing me some dot files and hidden directories. 

I have tried uploading an extension with developer mode, as a matter of fact that's the only way I've tried, I was using `inoxunpack`. I could try the alternatives listed on the README but at this point I'm more interested in sorting out my filepicker. When sites like Imgur ask me to upload an image I get the same issue.

**Comment by gcarq** [comment]
@faurehu Are you using firejail or something?

**Comment by gcarq** [comment]
Is this issue still relevant?

**Comment by gcarq** [comment]
Assuming this issue has been resolved. Feel free to reopen
