### ISSUE TITLE
Possible:  Code for 57

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#65]
https://u.teknik.io/ypxFU.7z

**Comment by triceratops1** [comment]
@lenormf @farenhu   
any help to compile is acepted

**Comment by DragoonAethis** [comment]
You didn't even test this?

**Comment by Eloston** [comment]
@DragoonAethis Probably not. triceratops1 contributes ideas, not code. Considering the redundancy with #64, #66, and this issue, I'm assuming triceratops1 is trying to get others to work on 57 as soon as possible (which is not uncommon behavior).

**Comment by lenormf** [comment]
I don't understand what this issue is about, and can't afford to spend resources on compiling unauthenticated code.

**Comment by triceratops1** [comment]
@lenormf  its my code (i've modified 3 patches from inox)   


for make possible built it :)

**Comment by triceratops1** [comment]
@perfect7gentleman @csmk  
can check it?

**Comment by Eloston** [comment]
@triceratops1 Please stop notifying everyone about updating to version 57. gcarq already said he will get to updating to version 57, and people can speak for themselves if they want to contribute. 

In other news, I'm almost done updating the patches to version 57. I'll update this comment when I have them pushed to ungoogled-chromium.

**Comment by gcarq** [comment]
Closed. See https://github.com/gcarq/inox-patchset/issues/64
