### ISSUE TITLE
V57: It works!

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#68]
32bit Works

64bit its building
https://build.opensuse.org/package/show/home:meh924f:archlinux/inox

**Comment by triceratops1** [comment]
http://download.opensuse.org/repositories/home:/meh924f:/archlinux/standard/i686/inox-57.0.2987.98-1-i686.pkg.tar.xz

**Comment by eloaders** [comment]
Distributor ID: ManjaroLinux
Description:    Manjaro Linux
Release:        17.0
Codename:       Gellivara

Linux michal-pc 4.10.1-1-MANJARO #1 SMP PREEMPT Sun Feb 26 15:19:27 UTC 2017 x86_64 GNU/Linux

```
[0320/064409.849973:ERROR:icu_util.cc(173)] Invalid file descriptor to ICU data received.
[0320/064409.850043:FATAL:content_main_runner.cc(696)] Check failed: base::i18n::InitializeICU(). 
#0 0x56542f777cfe <unknown>
#1 0x56542f7904ce <unknown>
#2 0x56542f42e5ae <unknown>
#3 0x56542f42d5dd <unknown>
#4 0x56542ded0074 ChromeMain
#5 0x7f467156c511 __libc_start_main
#6 0x56542decff0a _start

Przerwane (zrzut pamięci)
```

**Comment by triceratops1** [comment]
@eloaders   its fixed :) 
http://download.opensuse.org/repositories/home:/meh924f:/archlinux/standard/i686/inox-57.0.2987.98-1-i686.pkg.tar.xz

http://download.opensuse.org/repositories/home:/meh924f:/archlinux/standard/x86_64/inox-57.0.2987.98-1-x86_64.pkg.tar.xz

**Comment by eloaders** [comment]
Thank you, it works great.

**Comment by triceratops1** [comment]
i gave a new update (to 110)

http://download.opensuse.org/repositories/home:/meh924f:/archlinux/standard/i686/inox-57.0.2987.110-1-i686.pkg.tar.xz


64bit
its at queue

**Comment by triceratops1** [comment]
http://software.opensuse.org//download.html?project=home%3Ameh924f%3Aarchlinux&package=inox

**Comment by gcarq** [comment]
Closed. See https://github.com/gcarq/inox-patchset/issues/64
