### ISSUE TITLE
Question: How can i make a bundle? 

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#70]
how can i make a true bundle (inox at /opt with full libraries)?  

for let inox run at ancient systems (just like official google chrome) :dango:

**Comment by gcarq** [comment]
Which architecture and distribution you want to target? Do you want to use any system libraries?

**Comment by triceratops1** [comment]
archlinux 64  
or generic 64 

all libs bundled (like google :D)

**Comment by gcarq** [comment]
Use the arch chromium or inox PKGBUILD as base and play around with gn flags.
You should end up with something like:
```
gn gen out/Official "--args=is_debug=false is_official_build=true is_chrome_branded=true"
ninja -C out/Official
```
See [gn build configuration](https://www.chromium.org/developers/gn-build-configuration).
