### ISSUE TITLE
Enhacement: Mark as secure dark sites

### ISSUE THREAD

**Issue by triceratops1** [gcarq/inox-patchset#71]
sites from
tor: mark as secure (just like https) if the domain is .onion
i2p: mark as secure (just like https) if the domain is .i2p
freenet: mark as secure (just like https) if the url begins with localhost:8888
zeronet: mark as secure (just like https) if the url begins with localhost:43110

would be  extremely pretty

**Comment by gcarq** [comment]
Won't fix. A specific TLD or a host identifier does not make a connection secure.
