### ISSUE TITLE
Update to Chromium 58.X

### ISSUE THREAD

**Issue by nyancat18** [gcarq/inox-patchset#74]
chromium 58  its on the wild

can you update?

thanks

**Comment by nyancat18** [comment]
https://gist.github.com/nyancat18/62a261e9e0cb70a2fd83e0b2bc473439

**Comment by nyancat18** [comment]
ALERTS

you need replace makedepends
makedepends=('python2' 'gperf' 'yasm' 'mesa' 'ninja' 'nodejs' 'git')


and read
https://gist.github.com/nyancat18/3a4c65f88bcb42fa7cad5a028fda4662

**Comment by gcarq** [comment]
I will update it as soon as I'm back at home, which is at 02.05.2017

**Comment by nyancat18** [comment]
results: 001   its bad

0006 has redundant code
https://gist.github.com/nyancat18/d52d64148172c104bec02e20149986e4

0015 dont work

**Comment by gothmog123** [comment]
59 is out
