### ISSUE TITLE
License disallows usage in Inexor

### ISSUE THREAD

**Issue by a-teammate** [gcarq/inox-patchset#77]
Hey there

I'm coming here from ungoogled-chromium issue-tracker:

https://github.com/Eloston/ungoogled-chromium/issues/230

(And they told me they are using the GPL, since you are using the GPL ^^)
I'm really not sure in how far we can actually use these patches though, as we are a BSD style project.

So I'm quoting myself here:

>why add a license restriction when you're trying to free another software project? I mean you're intention is pretty good and its useful, but a lot of users can't get rid of the chrome stuff because of your license. 

Is there any chance you will change the license to be usable in Inexor?

**Comment by gcarq** [comment]
I answered in the issue you came from https://github.com/Eloston/ungoogled-chromium/issues/230. TL;DR: I'm happy to change the license in further releases.

**Comment by a-teammate** [comment]
Very cool! Thank you!
