### ISSUE TITLE
Update to 59.0.3071.86

### ISSUE THREAD

**Issue by xsmile** [gcarq/inox-patchset#79]
I adjusted the patchset for 59.0.3071.86 and the PKGBUILD based on the Arch Linux packages chromium, chromium-dev. Notable changes in contrast to the previous version are:
- patches for GCC7
- GTK3 support
- build option to enable VA-API

Issues I noticed so far:
- former "send-settings" checkbox is active, reset_profile_settings_overlay.html not used anymore
- patch to disable third party cookies is missing

This is by no means a final version and is only meant to help keeping the patchset up-to-date. The new chromium source can still contain unwanted changes not yet accounted for.

[Link removed]

**Comment by nyancat18** [comment]
@xsmile   can you give a temporary "Update"  

for let people with shitty computers update to chromium 59 (gcc7, apng and gtk3 based) ?

**Comment by xsmile** [comment]
No, sorry. gcarq should review it first. A working binary doesn't mean the patchset is working as intended.

**Comment by nyancat18** [comment]
@xsmile  i could test it  LOL

**Comment by Eloston** [comment]
@xsmile Does the VA-API patch work without degrading the browser experience? I've heard of some conflicts with the sandboxing mechanism before.

**Comment by nyancat18** [comment]
@eloston i offfer me as tester

**Comment by xsmile** [comment]
@Eloston: Can you provide an example? I read a while back that the patch needs further changes and might be problematic for Amd and Nvidia users.

I didn't run any extensive benchmarks. intel_gpu_top shows a GPU usage increase and the CPU usage drops by ~50% when viewing some sample videos on youtube in comparison to the official chromium package.
Apart from that I didn't notice anything unusual.

**Comment by Eloston** [comment]
@xsmile I am referring to [this comment](https://github.com/saiarcot895/chromium-ubuntu-build/issues/11#issuecomment-271501174). Do you need to make a component build and disable the GPU sandbox to get this patch to work?

Also, have you noticed any stability or perfomance issues over longer browsing sessions?

**Comment by xsmile** [comment]
@Eloston: No. However I can only speak for myself as an Intel GPU user.

I will try not to close the browser for a while and post an update if I notice anything unusual.

**Comment by Eloston** [comment]
@xsmile Oh, that's nice. I also use an Intel GPU, so I'll try this out when I get around to it.

**Comment by nyancat18** [comment]
https://chromereleases.googleblog.com/2017/06/stable-channel-update-for-desktop.html

**Comment by xsmile** [comment]
@Eloston Everything is fine so far.

I created PR #81 and I'm closing this issue.
