### ISSUE TITLE
outdated again :(

### ISSUE THREAD

**Issue by nyancat18** [gcarq/inox-patchset#86]
extra/chromium                         59.0.3071.109-1       -> 59.0.3071.115-1

**Comment by csmk** [comment]
No, it is not!  I mean, at least it's in sync with arch's repo.

**Comment by rEnr3n** [comment]
You can close this now. https://github.com/gcarq/inox-patchset/releases/tag/59.0.3071.115

**Comment by gcarq** [comment]
As mentioned inox-59.0.3071.115 has been released already.
