### ISSUE TITLE
Weird situation when installing Tampermonkey extension from their website

### ISSUE THREAD

**Issue by ThePierrezou** [gcarq/inox-patchset#9]
Hi,
I installed the extension from their website : http://tampermonkey.net
Their website is using the Chrome web store to install the extension, how it's possible that it worked ?
I'm using the lastest version from the AUR.
Thanks
ThePierrezou

**Comment by gcarq** [comment]
I found a Chromium feature called [Inline Installation](https://developer.chrome.com/webstore/inline_installation), it allows you install extensions without redirecting to WebStore, but very strange that it doesn't need the WebStore plugin at all.

Below is a html snippet to reproduce this, but it should give you `Err: Installs can only be initiated by one of the Chrome Web Store item's verified sites.`
```html
<!DOCTYPE html>
   
<head>
    <link rel="chrome-webstore-item" href="https://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo">
</head>

<body>
    <button onclick="install()">Add Extension</button>
</body>

<script>
    function install() {
        window.chrome.webstore.install(
                'https://chrome.google.com/webstore/detail/dhdgffkkebhmkfjojejmpbldmpobfkfo', 
                 e => { console.log('Done:', e) }, 
                 e => { console.log('Err:', e) });
    }
</script>
```

cheers

**Comment by ThePierrezou** [comment]
Thanks for explaining me how it works :)

**Comment by gcarq** [comment]
You're welcome!
