### ISSUE TITLE
abandoned  ?... sorry for this tittle

### ISSUE THREAD

**Issue by nyancat18** [gcarq/inox-patchset#95]
@gcarq sorry
but its this abandoned?

i've see that @xsmile  updated inox *lol*  

**i built it at 3.2 hours at a FX 8650 - 16 ram + HDD**

and after some hours for testing, i consider his patches as stable (browse ibs, torify, chat, facebook, videos and some pr0rn sites)

**Comment by nyancat18** [comment]
@xsmile @gcarq  

can we add an alert about buildtime?
just like this

**chromium needs significant IO** and if you've a HDD  you could need 3-4 hours for compile it **even with a strong cpu**,  you can build at a HDD **of course** but we reccomend you build it at **SSD/tmpFS**

**Comment by csmk** [comment]
I wish github had the option for _facepalm_ reaction.

**Comment by xsmile** [comment]
@nyancat18, Chromium develops rather fast and updating the patches with each new release is time-consuming. Recently I could dedicate some time to it but I can't make any promise for the future.
Additionally the patchset needs to be verified properly, see https://github.com/gcarq/inox-patchset/issues/64#issuecomment-287892793. I didn't do such intensive testing and would rather leave it to gcarq.
I'm sure gcarq will do another release when his CPU issues are resolved and he finds the time.
Luckily the patchset is here on GitHub and everyone can help keeping it up-to-date.

As far as I can tell, the README links to the official build instructions and covers build time.

Thanks, I added the dependency. Please use the issue page of my fork if you have any other problem with my changes.

**Comment by nyancat18** [comment]
i can help with testing

>my lasst testing gave the safebrowsing error at 15k

**Comment by nyancat18** [comment]
i can help with testing

>my lasst testing gave the safebrowsing error at 15k

**Comment by gcarq** [comment]
@nyancat18 no it's not abadoned, but as already mentioned, updating patches is very time consuming. On top of that was the holiday season and the broken CPU which slowed it down further.
