### ISSUE TITLE
Can i add my own branch

### ISSUE THREAD

**Issue by nyancat18** [gcarq/inox-patchset#97]
It just adds some *foerign* patches, just like the  "useful" @eloston 's patches from ungoogled-chromium,  update and use only the best iridium's patches (iridium has some crap,  some redundant and some unuseful)

>useful: dont give troubles with *previously patch applied*
>unuseful:  its an **insanely hardened**  "pseudoversion" from inox (even @eloston has enabled widewine)

If its possible, i want add my modification as a branch **i'm testing it, at 4 hours i'll report it**

**Comment by csmk** [comment]
Fork the project and do your own thing on your repo. Then you could do a PR later **if** you produce something useful.

**Comment by nyancat18** [comment]
thanks

@¢smk  at my mods     i've discovered that the gn flag    'enable_service_discovery=false'  provokes
https://p.teknik.io/Raw/olbFC


i'll test tomorrow all (removing the evil flag).. because here its 22:10   and if i rebuild .. i will spend more than midnight lol

**Comment by nyancat18** [comment]
@csmk    

new trouble *14:10*

https://p.teknik.io/lQLWD


can you explain me more about mdns *gn chromium flag*

for know if its deadly,  or  i could ignore it *until inox/ungooled/iridium  discovers a better workaround*

**Comment by csmk** [comment]
All I can say is that it's related to multicast DNS (name resolution service, service advertising, etc.). So I guess it leak some info about the local machine?!

> for know if its deadly, or i could ignore it until inox/ungooled/iridium discovers a better workaround

That's a subjective matter. Do some _DuckDuckGo-fu_ and make your call.
