### ISSUE TITLE
laggy UI

### ISSUE THREAD

**Issue by Inixi** [gcarq/inox-patchset#99]
When changing tabs in browser or moving tabs from one window to another the UI is laggy. Web View rendering is working properly - movie clips, 3d rendering, site scrolling etc.

**Comment by xsmile** [comment]
Hi, does it happen with the official Chromium package?
Which Inox release are you using?
Did it happen with previous Inox releases?
Is your system fully updated?

**Comment by Inixi** [comment]
Sorry for scarse information...
inox-bix 61.0.3163.100-1 @ Arch Linux 4.12.13-1
I have cleared all cache and local settings and seems that the browser is running fine. Probably it was some old extension which I have installed from Chrome Store...
Closing.
